<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="trace" nsURI="http://www.polarsys.org/time4sys/trace/1.0" nsPrefix="trace">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Return the Events of this slice ordered by timestamp."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" containment="true" eOpposite="#//Event/trace"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" lowerBound="1" eType="#//NFP_TimeInterval"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slices" upperBound="-1"
        eType="#//Slice" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xA;  See TraceCompass hostId.&#xA;[quote,TraceCompass]&#xA;------------&#xA;The host ID is not necessarily the hostname, but should be a unique identifier for the machine on which the trace was taken.&#xA;It can be used to determine if two traces were taken on the exact same machine (timestamp already synchronized, resources with same id are the same if taken at the same time, etc).&#xA;------------"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" eType="#//NFP_Duration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" lowerBound="1"
        eType="#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trace" lowerBound="1" eType="#//Trace"
        eOpposite="#//Trace/events"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="about" upperBound="-1"
        eType="#//Slice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="NFP_Duration" instanceClassName="org.polarsys.time4sys.marte.nfp.Duration"/>
  <eClassifiers xsi:type="ecore:EDataType" name="NFP_TimeInterval" instanceClassName="org.polarsys.time4sys.marte.nfp.TimeInterval"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SchedulingEventKind">
    <eLiterals name="ACTIVATED"/>
    <eLiterals name="RUNNING" value="1"/>
    <eLiterals name="SUSPENDED" value="2"/>
    <eLiterals name="BLOCKED" value="3"/>
    <eLiterals name="TERMINATED" value="4"/>
    <eLiterals name="DEADLINE" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//ResourceEventKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchedulingEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//SchedulingEventKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResourceEventKind">
    <eLiterals name="ACQUIRED"/>
    <eLiterals name="RELEASED" value="1"/>
    <eLiterals name="REQUESTED" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//MessageEventKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageEventKind">
    <eLiterals name="INSTANTIATED"/>
    <eLiterals name="TRANSMITTED" value="1"/>
    <eLiterals name="RECEIVED" value="2"/>
    <eLiterals name="ERROR" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slice">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A slice is an aggregation of Events so as to group them together in a logical way.&#xA;For instance, it could be:&#xA;&#xA;* the Gantt line view of a processor usage,&#xA;* an end-to-end dataflow,&#xA;* an end-to-end network packet travel,&#xA;* etc."/>
    </eAnnotations>
    <eOperations name="getHierarchicalName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="separator" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getAggregatedEvents" upperBound="-1" eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSubSlices" upperBound="-1"
        eType="#//Slice" containment="true" eOpposite="#//Slice/parent">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="wildcards" value=""/>
        <details key="name" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Slice"
        eOpposite="#//Slice/ownedSubSlices"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//SliceKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" eType="#//Properties"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSlices" upperBound="-1"
        eType="#//Slice"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SliceKind">
    <eLiterals name="OTHER"/>
    <eLiterals name="TASK" value="1"/>
    <eLiterals name="JOB" value="2"/>
    <eLiterals name="FUNCTION" value="3"/>
    <eLiterals name="FUNCTION_INSTANCE" value="4"/>
    <eLiterals name="PACKET" value="5"/>
    <eLiterals name="FRAME" value="6"/>
    <eLiterals name="LINK" value="7"/>
    <eLiterals name="RESOURCE" value="9"/>
    <eLiterals name="STATE" value="9"/>
    <eLiterals name="AUTOMATON" value="10"/>
    <eLiterals name="TEMPORAL_CHAIN" value="11"/>
    <eLiterals name="OS" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Properties">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" eType="#//NFP_TimeInterval"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockingTime" eType="#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionTime" eType="#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remainingTime" eType="#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" eType="#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="absoluteDeadline" eType="#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueChangeEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectValueChangeEvent" eSuperTypes="#//ValueChangeEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DurationValueChangeEvent" eSuperTypes="#//ValueChangeEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//NFP_Duration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSizeValueChangeEvent" eSuperTypes="#//ValueChangeEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//NFP_DataSize"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberValueChangeEvent" eSuperTypes="#//ValueChangeEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//ENumber"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ENumber" instanceClassName="java.lang.Number"/>
  <eClassifiers xsi:type="ecore:EDataType" name="NFP_DataSize" instanceClassName="org.polarsys.time4sys.marte.nfp.DataSize"/>
</ecore:EPackage>
