<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="analysis" nsURI="http://www.polarsys.org/time4sys/analysis/1.0"
    nsPrefix="analysis">
  <eClassifiers xsi:type="ecore:EDataType" name="NFP_Duration" instanceClassName="org.polarsys.time4sys.marte.nfp.Duration"/>
  <eClassifiers xsi:type="ecore:EDataType" name="NFP_TimeInterval" instanceClassName="org.polarsys.time4sys.marte.nfp.TimeInterval"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnalyzedSystem" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedulableElements" upperBound="-1"
        eType="#//SchedulableElement" containment="true" eOpposite="#//SchedulableElement/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedulers" upperBound="-1"
        eType="#//Scheduler" containment="true" eOpposite="#//Scheduler/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true" eOpposite="#//Resource/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintContainer" eType="#//ConstraintContainer"
        containment="true" eOpposite="#//ConstraintContainer/analyzedSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stimuli" upperBound="-1"
        eType="#//Stimulus" containment="true" eOpposite="#//Stimulus/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delays" upperBound="-1"
        eType="#//Delay" containment="true" eOpposite="#//Delay/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protectionProtocols" upperBound="-1"
        eType="#//ProtectionProtocol" containment="true" eOpposite="#//ProtectionProtocol/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mutexes" upperBound="-1"
        eType="#//MutualExclusionResource" containment="true" eOpposite="#//MutualExclusionResource/parent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultContainers" upperBound="-1"
        eType="#//ResultContainer" containment="true" eOpposite="#//ResultContainer/analyzedSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//Mapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Communication" eSuperTypes="#//SchedulableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bus" lowerBound="1" eType="#//CommunicationResource"
        eOpposite="#//CommunicationResource/communicationsAffectedOn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//ComputingResource" eOpposite="#//ComputingResource/linkedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communicationsAffectedOn"
        upperBound="-1" eType="#//Communication" eOpposite="#//Communication/bus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocolName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bandwidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputingResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasksAffectedOn" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/mappedTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedBy" upperBound="-1"
        eType="#//CommunicationResource" eOpposite="#//CommunicationResource/links"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintContainer" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analyzedSystem" eType="#//AnalyzedSystem"
        eOpposite="#//AnalyzedSystem/constraintContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Delay" eSuperTypes="#//EventModelContainer #//PortContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//AnalyzedSystem" eOpposite="#//AnalyzedSystem/delays"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedEvent" eType="#//EventModelContainer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="#//NFP_Duration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="offsets" upperBound="-1"
        eType="#//Offset" containment="true" eOpposite="#//Offset/eventModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" eType="#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jitter" eType="#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dmin" eType="#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//EventModelContainer"
        eOpposite="#//EventModelContainer/eventModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSporadic" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventModelContainer" abstract="true"
      eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventModel" eType="#//EventModel"
        containment="true" eOpposite="#//EventModel/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fragment" eSuperTypes="#//NamedElement #//SynchronizableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Fragment"
        eOpposite="#//Fragment/previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//Fragment"
        eOpposite="#//Fragment/next"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" lowerBound="1" eType="#//Task"
        eOpposite="#//Task/fragments"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CET" eType="#//NFP_TimeInterval"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InputJoinBehaviorKind">
    <eLiterals name="Merge"/>
    <eLiterals name="Join" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveFrom" eType="#//OutputPort"
        eOpposite="#//OutputPort/sendTo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputStimulus" eSuperTypes="#//Stimulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPorts" upperBound="-1"
        eType="#//OutputPort" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="system" eType="#//AnalyzedSystem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemoryResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MutualExclusionResource" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//SynchronizableElement" eOpposite="#//SynchronizableElement/lockedMutexes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protectionParameters" upperBound="-1"
        eType="#//ProtectionParameterValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protectedBy" lowerBound="1"
        eType="#//ProtectionProtocol" eOpposite="#//ProtectionProtocol/mutexes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//AnalyzedSystem" eOpposite="#//AnalyzedSystem/mutexes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Offset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventModel" lowerBound="1"
        eType="#//EventModel" eOpposite="#//EventModel/offsets"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendTo" eType="#//InputPort"
        eOpposite="#//InputPort/receiveFrom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputStimulus" eSuperTypes="#//Stimulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPorts" upperBound="-1"
        eType="#//InputPort" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//EventModelContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//PortContainer"
        eOpposite="#//PortContainer/ports"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//Port" containment="true" eOpposite="#//Port/parent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behaviorKind" eType="#//InputJoinBehaviorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtectionParameterValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//RequiredProtectionParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtectionProtocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocolName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mutexes" upperBound="-1"
        eType="#//MutualExclusionResource" eOpposite="#//MutualExclusionResource/protectedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredParameters" upperBound="-1"
        eType="#//RequiredProtectionParameter" containment="true" eOpposite="#//RequiredProtectionParameter/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceParameterValue"
        upperBound="-1" eType="#//ResourceProtectionParameterValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//AnalyzedSystem" eOpposite="#//AnalyzedSystem/protectionProtocols"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredProtectionParameter" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//ProtectionProtocol" eOpposite="#//ProtectionProtocol/requiredParameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredSchedulingParameter" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//Scheduler" eOpposite="#//Scheduler/requiredParameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduler" lowerBound="1"
        eType="#//Scheduler" eOpposite="#//Scheduler/usedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//AnalyzedSystem" eOpposite="#//AnalyzedSystem/resources"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speedFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" eType="#//NFP_Duration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceSchedulingParameterValue" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResultContainer" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="analyzedSystem" eType="#//AnalyzedSystem"
        eOpposite="#//AnalyzedSystem/resultContainers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchedulableElement" abstract="true"
      eSuperTypes="#//EventModelContainer #//PortContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//AnalyzedSystem" eOpposite="#//AnalyzedSystem/schedulableElements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduledBy" eType="#//Scheduler"
        eOpposite="#//Scheduler/scheduledElements"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CET" lowerBound="1" eType="#//NFP_TimeInterval"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedulingParameters" upperBound="-1"
        eType="#//SchedulerParameterValue" containment="true" eOpposite="#//SchedulerParameterValue/parent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originalName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchedulerParameterValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//RequiredSchedulingParameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//SchedulableElement" eOpposite="#//SchedulableElement/schedulingParameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scheduler" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="policyKind" lowerBound="1"
        eType="#//SchedulerPolicyKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduledElements" upperBound="-1"
        eType="#//SchedulableElement" eOpposite="#//SchedulableElement/scheduledBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedBy" eType="#//Resource"
        eOpposite="#//Resource/scheduler"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredParameters" upperBound="-1"
        eType="#//RequiredSchedulingParameter" containment="true" eOpposite="#//RequiredSchedulingParameter/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//AnalyzedSystem"
        eOpposite="#//AnalyzedSystem/schedulers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceParameterValue"
        upperBound="-1" eType="#//ResourceSchedulingParameterValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preferredPolicy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchedulerPolicyKind">
    <eLiterals name="NoContention"/>
    <eLiterals name="FixedPriority" value="1"/>
    <eLiterals name="EDF" value="2"/>
    <eLiterals name="FIFO" value="3"/>
    <eLiterals name="TDMA" value="4"/>
    <eLiterals name="RoundRobin" value="5" literal="RoundRobin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stimulus" abstract="true" eSuperTypes="#//EventModelContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//AnalyzedSystem" eOpposite="#//AnalyzedSystem/stimuli"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronizableElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lockedMutexes" upperBound="-1"
        eType="#//MutualExclusionResource" eOpposite="#//MutualExclusionResource/elements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//SchedulableElement #//SynchronizableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappedTo" lowerBound="1"
        eType="#//ComputingResource" eOpposite="#//ComputingResource/tasksAffectedOn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" lowerBound="1"
        upperBound="-1" eType="#//Fragment" containment="true" eOpposite="#//Fragment/task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" lowerBound="1" eType="#//Fragment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockingTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceProtectionParameterValue" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TwcaEventModel" eSuperTypes="#//EventModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deltamin_func" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
