<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="library" nsURI="http://www.polarsys.org/time4sys/library/1.0"
    nsPrefix="library">
  <eClassifiers xsi:type="ecore:EClass" name="TDMA" eSuperTypes="grm.ecore#//SchedulingPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slot" unique="false" upperBound="-1"
        eType="ecore:EDataType gqam.ecore#//NFP_Duration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeadlineMonotonicSchedulingPolicy" eSuperTypes="grm.ecore#//SchedulingPolicy"/>
  <eClassifiers xsi:type="ecore:EClass" name="RateMonotonicSchedulingPolicy" eSuperTypes="grm.ecore#//SchedulingPolicy"/>
  <eClassifiers xsi:type="ecore:EClass" name="HardwareCANBus" eSuperTypes="hrm.ecore#//HardwareBus"/>
</ecore:EPackage>
