<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sam" nsURI="http://www.polarsys.org/time4sys/marte/sam/1.0"
    nsPrefix="sam">
  <eClassifiers xsi:type="ecore:EClass" name="EndToEndFlow" eSuperTypes="core_elements.ecore#//NamedElement nfp_annotation.ecore#//AnnotatedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="End-to-end flows describe a unit of processing work in the analyzed system, which contend for use of the processing&#xA;resources. This is a conceptual entity only, which is represented by its concrete elements: end-to-end stimuli and end-to-&#xA;end response."/>
    </eAnnotations>
    <eOperations name="findStepsOnPath" upperBound="-1" eType="ecore:EClass gqam.ecore#//BehaviorScenario">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return all steps and sub-BehaviorScenarios who are on the path from stimuli to response.&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endToEndStimuli" upperBound="-1"
        eType="ecore:EClass gqam.ecore#//WorkloadEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endToEndScenario" lowerBound="1"
        eType="ecore:EClass gqam.ecore#//BehaviorScenario"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSchedulable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schedulabilitySlack" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endToEndTime" eType="ecore:EDataType gqam.ecore#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endToEndDeadline" eType="ecore:EDataType gqam.ecore#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timing" upperBound="-1"
        eType="ecore:EClass gqam.ecore#//TimedObserver" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="NFP_Duration" instanceClassName="org.polarsys.time4sys.marte.nfp.Duration"/>
  <eClassifiers xsi:type="ecore:EClass" name="SchedulingObserver" eSuperTypes="gqam.ecore#//TimedObserver">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suspensions" eType="#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockingTime" eType="#//NFP_Duration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overlaps" eType="#//NFP_Duration"/>
  </eClassifiers>
</ecore:EPackage>
