<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="srm" nsURI="http://www.polarsys.org/time4sys/marte/srm/1.0"
    nsPrefix="srm">
  <eClassifiers xsi:type="ecore:EEnum" name="AccessPolicyKind">
    <eLiterals name="Read"/>
    <eLiterals name="Write" value="1"/>
    <eLiterals name="ReadWrite" value="2"/>
    <eLiterals name="Undef" value="3"/>
    <eLiterals name="Other" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alarm" eSuperTypes="#//InterruptResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timers" upperBound="-1"
        eType="#//SoftwareTimerResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isWatchdog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConcurrentAccesProtocolKind">
    <eLiterals name="PCP"/>
    <eLiterals name="PIP" value="1"/>
    <eLiterals name="NoPreemption" value="2"/>
    <eLiterals name="Undef" value="3"/>
    <eLiterals name="Other" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceBroker" eSuperTypes="grm.ecore#//ResourceBroker #//SoftwareResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//DeviceResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessPolicy" eType="#//AccessPolicyKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBuffered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="closeServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="openServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writeServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InterruptKind">
    <eLiterals name="HardwareInterruption"/>
    <eLiterals name="ProcessorDetectedException" value="1"/>
    <eLiterals name="ProgrammedException" value="2"/>
    <eLiterals name="Undef" value="3"/>
    <eLiterals name="Other" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="QueuePolicyKind">
    <eLiterals name="FIFO"/>
    <eLiterals name="LIFO" value="1"/>
    <eLiterals name="Priority" value="2"/>
    <eLiterals name="Undef" value="3"/>
    <eLiterals name="Other" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterruptResource" eSuperTypes="#//SoftwareConcurrentResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//InterruptKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMaskable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routineConnectServices"
        upperBound="-1" eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routineDisconnectServices"
        upperBound="-1" eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maskElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vectorElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isrEntryPoints" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemoryBroker" eSuperTypes="grm.ecore#//ResourceBroker #//SoftwareResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lockServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unlockServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unmapServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memories" upperBound="-1"
        eType="ecore:EClass grm.ecore#//StorageResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessPolicy" eType="#//AccessPolicyKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memoryBlockAddressElements"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memoryBlockSizeElements"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemoryPartition" eSuperTypes="#//SoftwareResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="concurrentResources" lowerBound="1"
        upperBound="-1" eType="#//SoftwareConcurrentResource" containment="true" eOpposite="#//SoftwareConcurrentResource/adressSpace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forkServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exitServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memorySpaces" upperBound="-1"
        eType="ecore:EClass grm.ecore#//StorageResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageComResource" eSuperTypes="#//SoftwareCommunicationResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFixedMessageSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageSizeElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mechanism" eType="#//MessageResourceKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageQueuePolicy" eType="#//QueuePolicyKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageQueueCapacityElements"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageResourceKind">
    <eLiterals name="MessageQueue"/>
    <eLiterals name="Pipe" value="1"/>
    <eLiterals name="Blackboard" value="2"/>
    <eLiterals name="Undef" value="3"/>
    <eLiterals name="Other" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MutualExclusionResourceKind">
    <eLiterals name="BooleanSemaphore"/>
    <eLiterals name="CountSemaphore" value="1"/>
    <eLiterals name="Mutex" value="2"/>
    <eLiterals name="Undef" value="3"/>
    <eLiterals name="Other" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotificationResource" eSuperTypes="#//SoftwareSynchronizationResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flushServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signalServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="waitServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clearServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="policy" lowerBound="1"
        eType="#//OccurencePolicyKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mechanism" lowerBound="1"
        eType="#//NotificationResourceKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="occurenceCountElements"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maskElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NotificationResourceKind">
    <eLiterals name="Barrier"/>
    <eLiterals name="Event" value="1"/>
    <eLiterals name="Undef" value="2"/>
    <eLiterals name="Other" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OccurencePolicyKind">
    <eLiterals name="Memorized"/>
    <eLiterals name="Bounded" value="1"/>
    <eLiterals name="Memoryless" value="2"/>
    <eLiterals name="Undef" value="3"/>
    <eLiterals name="Other" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SharedDataComResource" eSuperTypes="#//SoftwareCommunicationResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="readServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writeServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareAccessService" eSuperTypes="grm.ecore#//ResourceService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isModifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessedElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareArchitecture" eSuperTypes="#//SoftwareResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareCommunicationResource" abstract="true"
      eSuperTypes="#//SoftwareInteractionResource grm.ecore#//CommunicationMedia"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareConcurrentResource" abstract="true"
      eSuperTypes="#//SoftwareResource grm.ecore#//ConcurrencyResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activateServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resumeServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suspendServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enableConcurrencyServices"
        upperBound="-1" eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disableConcurrencyServices"
        upperBound="-1" eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terminateServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adressSpace" eType="#//MemoryPartition"
        eOpposite="#//MemoryPartition/concurrentResources"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activationCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priorityElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stackSizeElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="heapSizeElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sharedDataResources" upperBound="-1"
        eType="#//SharedDataComResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageResources" upperBound="-1"
        eType="#//MessageComResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mutualExclusionResources"
        upperBound="-1" eType="#//SoftwareMutualExclusionResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notificationResources"
        upperBound="-1" eType="#//NotificationResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entryPoints" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrivalPattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareConnector" eSuperTypes="grm.ecore#//ResourceConnector"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareInteractionResource" abstract="true"
      eSuperTypes="grm.ecore#//CommunicationEndPoint #//SoftwareResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isIntraMemoryPartitionInteraction"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitingQueuePolicy" eType="#//QueuePolicyKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitingQueueCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitingPolicyElements"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareInterface" eSuperTypes="grm.ecore#//ResourceInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareInterfacePackage" eSuperTypes="grm.ecore#//ResourcePackage"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareMutualExclusionResource" eSuperTypes="#//SoftwareSynchronizationResource grm.ecore#//MutualExclusionResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="concurrentAccessProtocol"
        eType="#//ConcurrentAccesProtocolKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mechanism" eType="#//MutualExclusionResourceKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="acquireServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="releaseServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessTokenElements" upperBound="-1"
        eType="ecore:EClass grm.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwarePort" eSuperTypes="grm.ecore#//ResourcePort"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareResource" eSuperTypes="grm.ecore#//ResourceManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="createServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deleteServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializeServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memorySizeFootprint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifierElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareResourcePackage" eSuperTypes="grm.ecore#//ResourcePackage"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareSchedulableResource" eSuperTypes="grm.ecore#//SchedulableResource #//SoftwareConcurrentResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStaticSchedulingFeature"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPreemptable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deadlineElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deadlineTypeElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeSliceElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yieldServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delayServices" upperBound="-1"
        eType="ecore:EClass grm.ecore#//ResourceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduler" lowerBound="1"
        eType="#//SoftwareScheduler" eOpposite="#//SoftwareScheduler/scheduledResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareScheduler" eSuperTypes="grm.ecore#//Scheduler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduledResource" upperBound="-1"
        eType="#//SoftwareSchedulableResource" eOpposite="#//SoftwareSchedulableResource/scheduler"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareService" eSuperTypes="grm.ecore#//ResourceService"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareSynchronizationResource" abstract="true"
      eSuperTypes="#//SoftwareInteractionResource grm.ecore#//SynchResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareTimerResource" eSuperTypes="grm.ecore#//TimerResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
