<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="time4sys" nsURI="http://www.polarsys.org/time4sys/1.0" nsPrefix="time4sys">
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="design" eType="ecore:EClass ../../org.polarsys.time4sys.marte/model/design.ecore#//DesignModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="ecore:EClass ../../org.polarsys.time4sys.mapping/model/mapping.ecore#//Mapping"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" upperBound="-1"
        eType="ecore:EClass ../../org.polarsys.time4sys.trace/model/trace.ecore#//Trace"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="derivations" upperBound="-1"
        eType="ecore:EClass ../../org.polarsys.time4sys.marte/model/design.ecore#//DesignModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" upperBound="-1"
        eType="#//Transformation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simulations" upperBound="-1"
        eType="#//Simulation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformation" eSuperTypes="../../org.polarsys.time4sys.marte/model/core_elements.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="ecore:EClass ../../org.polarsys.time4sys.mapping/model/mapping.ecore#//Mapping"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Simulation" eSuperTypes="../../org.polarsys.time4sys.marte/model/core_elements.ecore#//ModelElement">
    <eOperations name="getDesignModel" eType="ecore:EClass ../../org.polarsys.time4sys.marte/model/design.ecore#//DesignModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="ecore:EClass ../../org.polarsys.time4sys.mapping/model/mapping.ecore#//Mapping"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trace" lowerBound="1" eType="ecore:EClass ../../org.polarsys.time4sys.trace/model/trace.ecore#//Trace"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
</ecore:EPackage>
