<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="components" nsURI="org.polarsys.time4sys.marte.analysisrepository.ui.graphmodel"
    nsPrefix="gm">
  <eClassifiers xsi:type="ecore:EClass" name="GraphModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allNodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allConnections" upperBound="-1"
        eType="#//Connection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//GraphComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textColor" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="#//GraphComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="BLUE"/>
    <eLiterals name="RED" value="1" literal="RED"/>
    <eLiterals name="YELLOW" value="2"/>
    <eLiterals name="BLACK" value="3"/>
    <eLiterals name="GREEN" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphComponent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
  </eClassifiers>
</ecore:EPackage>
